# Generated by Django 5.2.16 on 2026-07-12 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_expense_fuellog_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='joining_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuellog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='end_odometer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Liters', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_odometer',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
