# Generated by Django 4.2.30 on 2026-07-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_driver_is_active_trip_is_active_vehicle_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('cng', 'CNG'), ('electric', 'Electric')], max_length=20),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='vendor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('fuel', 'Fuel'), ('maintenance', 'Maintenance'), ('parking', 'Parking'), ('toll', 'Toll'), ('repair', 'Repair'), ('miscellaneous', 'Miscellaneous'), ('other', 'Other')], max_length=20),
        ),
    ]
