# Generated by Django 4.2.30 on 2026-07-12 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_expense_is_active_expense_remarks_fuellog_fuel_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('license_expiry', 'License Expiry'), ('insurance_expiry', 'Insurance Expiry'), ('service_due', 'Service Due'), ('maintenance_started', 'Maintenance Started'), ('trip_completed', 'Trip Completed'), ('trip_delayed', 'Trip Delayed'), ('fuel_cost_spike', 'Fuel Cost Spike'), ('expense_limit', 'Expense Limit Exceeded')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'High/Alert')], default='info', max_length=20)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('rc', 'Registration Certificate (RC)'), ('insurance', 'Insurance Policy'), ('puc', 'PUC Certificate'), ('permit', 'National/State Permit')], max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='vehicle_docs/')),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='transport.vehicle')),
            ],
        ),
    ]
